const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');

const headers = ['ID', 'Patient Name', 'Phone', 'Language', 'Date', 'Status', 'SMS Status', 'WhatsApp Status', 'Voice Status'];

const normalizeValue = (value) => {
  if (value instanceof Date) {
    return value.toISOString().slice(0, 10);
  }
  return value ?? '';
};

const rowToArray = (row) => [
  row.id,
  row.patient_name,
  row.patient_phone,
  row.language,
  normalizeValue(row.appointment_date),
  row.status,
  row.sms_status || (row.reminder_sent ? 'Sent' : 'Pending'),
  row.whatsapp_status || 'Pending',
  row.voice_status || 'Pending'
];

/**
 * Compile data rows into clean CSV
 */
const toCsv = (rows) => {
  const escapeCsv = (value) => `"${String(normalizeValue(value)).replace(/"/g, '""')}"`;
  return [headers, ...rows.map(rowToArray)]
    .map((row) => row.map(escapeCsv).join(','))
    .join('\n');
};

/**
 * Compile data rows into a styled modern binary Excel sheet (.xlsx)
 */
const toExcel = async (rows, title = 'Dermatology Report', user = null) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Report');

  // Add branding blocks
  worksheet.addRow([]);
  const brandRow = worksheet.addRow(['Acharya Vinoba Bhave Rural Hospital']);
  brandRow.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FF1E3A8A' } };
  
  const deptRow = worksheet.addRow(['Department of Dermatology | Dermatologist Visit Reminder System']);
  deptRow.font = { name: 'Arial', size: 11, bold: true, color: { argb: 'FF475569' } };

  const generatedByStr = user ? `${user.username} (${user.role})` : 'System Administrator';
  const metaRow = worksheet.addRow([
    `Generated Date: ${new Date().toLocaleString()} | Period: ${title.toUpperCase()} | Generated By: ${generatedByStr}`
  ]);
  metaRow.font = { name: 'Arial', size: 9, italic: true, color: { argb: 'FF64748B' } };
  
  // Calculate summary metrics
  const total = rows.length;
  const visited = rows.filter(r => r.visited).length;
  const missed = rows.filter(r => r.status === 'missed').length;
  const upcoming = rows.filter(r => !r.visited && r.status !== 'missed').length;

  worksheet.addRow([]);
  const statsRow = worksheet.addRow([
    `SUMMARY STATISTICS  -  Total: ${total} | Visited: ${visited} | Missed: ${missed} | Upcoming: ${upcoming}`
  ]);
  statsRow.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FF0F172A' } };
  worksheet.addRow([]);

  // Add headers
  const headerRow = worksheet.addRow(headers);
  headerRow.font = { name: 'Arial', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
  headerRow.eachCell((cell) => {
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1E3A8A' }
    };
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      bottom: { style: 'medium', color: { argb: 'FF1E3A8A' } },
      right: { style: 'thin', color: { argb: 'FFCBD5E1' } }
    };
  });
  
  // Add data rows
  rows.forEach((row, idx) => {
    const arr = rowToArray(row);
    const dataRow = worksheet.addRow(arr);
    
    const isEven = idx % 2 === 0;
    dataRow.eachCell((cell, colNumber) => {
      cell.font = { name: 'Arial', size: 10 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: isEven ? 'FFFFFFFF' : 'FFF8FAFC' }
      };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };

      // Force phone numbers as text columns to avoid scientific notations
      if (colNumber === 3) {
        cell.numFmt = '@';
      }
    });
  });

  // Adjust column widths
  worksheet.columns.forEach((column) => {
    column.width = 18;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
};

/**
 * Generate beautifully styled PDF layout using PDFKit supporting multi-page rendering
 */
const toPdf = (rows, title = 'Dermatology Report', user = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 30, size: 'A4', bufferPages: true });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      // Draw Top Letterhead
      doc.fillColor('#1e3a8a')
         .fontSize(16)
         .font('Helvetica-Bold')
         .text('ACHARYA VINOBA BHAVE RURAL HOSPITAL', 30, 30);

      doc.fillColor('#475569')
         .fontSize(10)
         .font('Helvetica-Bold')
         .text('Dermatology Department | System Name: Dermatology Reminder System', 30, 52);

      const generatedByStr = user ? `${user.username} (${user.role})` : 'System Administrator';
      doc.fillColor('#64748b')
         .fontSize(8)
         .font('Helvetica-Oblique')
         .text(`Generated Date: ${new Date().toLocaleString()} | Period: ${title.toUpperCase()} | Generated By: ${generatedByStr}`, 30, 68);

      // Rule separator
      doc.strokeColor('#cbd5e1')
         .lineWidth(1)
         .moveTo(30, 80)
         .lineTo(565, 80)
         .stroke();

      // Summary Statistics Header
      const total = rows.length;
      const visited = rows.filter(r => r.visited).length;
      const missed = rows.filter(r => r.status === 'missed').length;
      const upcoming = rows.filter(r => !r.visited && r.status !== 'missed').length;

      doc.fillColor('#f8fafc')
         .rect(30, 90, 535, 30)
         .fill();
      
      doc.fillColor('#0f172a')
         .fontSize(9)
         .font('Helvetica-Bold')
         .text(`SUMMARY STATISTICS  -  Total: ${total}   |   Visited: ${visited}   |   Missed: ${missed}   |   Upcoming: ${upcoming}`, 40, 100);

      // Column widths (Total Width: 535)
      const columns = [
        { header: 'ID', width: 25 },
        { header: 'Patient Name', width: 85 },
        { header: 'Phone', width: 70 },
        { header: 'Lang', width: 35 },
        { header: 'Date', width: 55 },
        { header: 'Status', width: 50 },
        { header: 'SMS', width: 55 },
        { header: 'WhatsApp', width: 80 },
        { header: 'Voice', width: 80 }
      ];

      let startX = 30;
      let startY = 135;

      // Draw Table Header
      doc.fillColor('#1e3a8a')
         .rect(30, startY, 535, 20)
         .fill();

      doc.fillColor('#ffffff')
         .fontSize(8)
         .font('Helvetica-Bold');

      let curX = startX;
      columns.forEach(col => {
        doc.text(col.header, curX + 4, startY + 6, { width: col.width - 8, align: 'left' });
        curX += col.width;
      });

      startY += 20;

      // Draw Rows
      rows.forEach((row, rowIndex) => {
        const arr = rowToArray(row);

        // Manage pagination wraps
        if (startY > 740) {
          doc.addPage();
          startY = 40;

          // Header repeat
          doc.fillColor('#1e3a8a')
             .rect(30, startY, 535, 20)
             .fill();

          doc.fillColor('#ffffff')
             .fontSize(8)
             .font('Helvetica-Bold');

          let tempX = startX;
          columns.forEach(col => {
            doc.text(col.header, tempX + 4, startY + 6, { width: col.width - 8, align: 'left' });
            tempX += col.width;
          });

          startY += 20;
        }

        // Zebra rows
        if (rowIndex % 2 !== 0) {
          doc.fillColor('#f8fafc')
             .rect(30, startY, 535, 18)
             .fill();
        }

        // Stroke line
        doc.strokeColor('#e2e8f0')
           .lineWidth(0.5)
           .moveTo(30, startY + 18)
           .lineTo(565, startY + 18)
           .stroke();

        doc.fillColor('#1f2937')
           .fontSize(7.5)
           .font('Helvetica');

        let colX = startX;
        arr.forEach((val, colIdx) => {
          const text = String(val ?? '');
          doc.text(text, colX + 4, startY + 5, { width: columns[colIdx].width - 8, height: 12, ellipsis: true });
          colX += columns[colIdx].width;
        });

        startY += 18;
      });

      // Render footers across all generated pages
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        
        doc.strokeColor('#cbd5e1')
           .lineWidth(0.5)
           .moveTo(30, 800)
           .lineTo(565, 800)
           .stroke();

        doc.fillColor('#94a3b8')
           .fontSize(7)
           .font('Helvetica')
           .text('Copyright Acharya Vinoba Bhave Rural Hospital - Dermatology Department | Confidentiality Asserted', 30, 810);

        doc.text(`Page ${i + 1} of ${range.count}`, 520, 810, { align: 'right' });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = {
  toCsv,
  toExcel,
  toPdf
};
